services:

 web:
  build:
   context: .
  volumes:
    - media:/code/media
  ports:
    - "9002:80"
  environment:
    - SQLALCHEMY_DATABASE_URI=postgresql://postgres:postgres@db/postgres
  depends_on:
   - db

 db:
  image: postgres:15
  environment:
    - POSTGRES_PASSWORD=postgres
  volumes:
    - pgdata:/var/lib/postgresql/data

volumes:
  media:
  pgdata:
